# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import memvid_pb2 as memvid_dot_v1_dot_memvid__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memvid/v1/memvid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemvidServiceStub(object):
    """MemvidService provides semantic search over resume content stored in .mv2 files.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/memvid.v1.MemvidService/Search',
                request_serializer=memvid_dot_v1_dot_memvid__pb2.SearchRequest.SerializeToString,
                response_deserializer=memvid_dot_v1_dot_memvid__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/memvid.v1.MemvidService/GetState',
                request_serializer=memvid_dot_v1_dot_memvid__pb2.GetStateRequest.SerializeToString,
                response_deserializer=memvid_dot_v1_dot_memvid__pb2.GetStateResponse.FromString,
                _registered_method=True)


class MemvidServiceServicer(object):
    """MemvidService provides semantic search over resume content stored in .mv2 files.
    """

    def Search(self, request, context):
        """Search performs semantic search over the loaded memvid index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """GetState retrieves a memory card entity by name (O(1) lookup).
        Used for profile metadata retrieval without search truncation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemvidServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=memvid_dot_v1_dot_memvid__pb2.SearchRequest.FromString,
                    response_serializer=memvid_dot_v1_dot_memvid__pb2.SearchResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=memvid_dot_v1_dot_memvid__pb2.GetStateRequest.FromString,
                    response_serializer=memvid_dot_v1_dot_memvid__pb2.GetStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memvid.v1.MemvidService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memvid.v1.MemvidService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemvidService(object):
    """MemvidService provides semantic search over resume content stored in .mv2 files.
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memvid.v1.MemvidService/Search',
            memvid_dot_v1_dot_memvid__pb2.SearchRequest.SerializeToString,
            memvid_dot_v1_dot_memvid__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memvid.v1.MemvidService/GetState',
            memvid_dot_v1_dot_memvid__pb2.GetStateRequest.SerializeToString,
            memvid_dot_v1_dot_memvid__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthStub(object):
    """Health provides service health checking following gRPC health checking protocol.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/memvid.v1.Health/Check',
                request_serializer=memvid_dot_v1_dot_memvid__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=memvid_dot_v1_dot_memvid__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServicer(object):
    """Health provides service health checking following gRPC health checking protocol.
    """

    def Check(self, request, context):
        """Check returns the current health status of the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=memvid_dot_v1_dot_memvid__pb2.HealthCheckRequest.FromString,
                    response_serializer=memvid_dot_v1_dot_memvid__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memvid.v1.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memvid.v1.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Health provides service health checking following gRPC health checking protocol.
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memvid.v1.Health/Check',
            memvid_dot_v1_dot_memvid__pb2.HealthCheckRequest.SerializeToString,
            memvid_dot_v1_dot_memvid__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
