# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memvid/v1/memvid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'memvid/v1/memvid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16memvid/v1/memvid.proto\x12\tmemvid.v1\"D\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x15\n\rsnippet_chars\x18\x03 \x01(\x05\"Y\n\x0eSearchResponse\x12\"\n\x04hits\x18\x01 \x03(\x0b\x32\x14.memvid.v1.SearchHit\x12\x12\n\ntotal_hits\x18\x02 \x01(\x05\x12\x0f\n\x07took_ms\x18\x03 \x01(\x05\"H\n\tSearchHit\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0f\n\x07snippet\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"/\n\x0fGetStateRequest\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\t\x12\x0c\n\x04slot\x18\x02 \x01(\t\"\x96\x01\n\x10GetStateResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0e\n\x06\x65ntity\x18\x02 \x01(\t\x12\x35\n\x05slots\x18\x03 \x03(\x0b\x32&.memvid.v1.GetStateResponse.SlotsEntry\x1a,\n\nSlotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xab\x01\n\x13HealthCheckResponse\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.memvid.v1.HealthCheckResponse.Status\x12\x13\n\x0b\x66rame_count\x18\x02 \x01(\x05\x12\x13\n\x0bmemvid_file\x18\x03 \x01(\t\"3\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\x93\x01\n\rMemvidService\x12=\n\x06Search\x12\x18.memvid.v1.SearchRequest\x1a\x19.memvid.v1.SearchResponse\x12\x43\n\x08GetState\x12\x1a.memvid.v1.GetStateRequest\x1a\x1b.memvid.v1.GetStateResponse2P\n\x06Health\x12\x46\n\x05\x43heck\x12\x1d.memvid.v1.HealthCheckRequest\x1a\x1e.memvid.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memvid.v1.memvid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATERESPONSE_SLOTSENTRY']._loaded_options = None
  _globals['_GETSTATERESPONSE_SLOTSENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=37
  _globals['_SEARCHREQUEST']._serialized_end=105
  _globals['_SEARCHRESPONSE']._serialized_start=107
  _globals['_SEARCHRESPONSE']._serialized_end=196
  _globals['_SEARCHHIT']._serialized_start=198
  _globals['_SEARCHHIT']._serialized_end=270
  _globals['_GETSTATEREQUEST']._serialized_start=272
  _globals['_GETSTATEREQUEST']._serialized_end=319
  _globals['_GETSTATERESPONSE']._serialized_start=322
  _globals['_GETSTATERESPONSE']._serialized_end=472
  _globals['_GETSTATERESPONSE_SLOTSENTRY']._serialized_start=428
  _globals['_GETSTATERESPONSE_SLOTSENTRY']._serialized_end=472
  _globals['_HEALTHCHECKREQUEST']._serialized_start=474
  _globals['_HEALTHCHECKREQUEST']._serialized_end=511
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=514
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=685
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_start=634
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_end=685
  _globals['_MEMVIDSERVICE']._serialized_start=688
  _globals['_MEMVIDSERVICE']._serialized_end=835
  _globals['_HEALTH']._serialized_start=837
  _globals['_HEALTH']._serialized_end=917
# @@protoc_insertion_point(module_scope)
